/*
JQuants

JQuants

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jquants

import (
	"encoding/json"
)

// checks if the MailPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailPassword{}

// MailPassword mail and password
type MailPassword struct {
	Mailaddress *string `json:"mailaddress,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewMailPassword instantiates a new MailPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailPassword() *MailPassword {
	this := MailPassword{}
	return &this
}

// NewMailPasswordWithDefaults instantiates a new MailPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailPasswordWithDefaults() *MailPassword {
	this := MailPassword{}
	return &this
}

// GetMailaddress returns the Mailaddress field value if set, zero value otherwise.
func (o *MailPassword) GetMailaddress() string {
	if o == nil || IsNil(o.Mailaddress) {
		var ret string
		return ret
	}
	return *o.Mailaddress
}

// GetMailaddressOk returns a tuple with the Mailaddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPassword) GetMailaddressOk() (*string, bool) {
	if o == nil || IsNil(o.Mailaddress) {
		return nil, false
	}
	return o.Mailaddress, true
}

// HasMailaddress returns a boolean if a field has been set.
func (o *MailPassword) HasMailaddress() bool {
	if o != nil && !IsNil(o.Mailaddress) {
		return true
	}

	return false
}

// SetMailaddress gets a reference to the given string and assigns it to the Mailaddress field.
func (o *MailPassword) SetMailaddress(v string) {
	o.Mailaddress = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *MailPassword) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailPassword) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *MailPassword) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *MailPassword) SetPassword(v string) {
	o.Password = &v
}

func (o MailPassword) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mailaddress) {
		toSerialize["mailaddress"] = o.Mailaddress
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableMailPassword struct {
	value *MailPassword
	isSet bool
}

func (v NullableMailPassword) Get() *MailPassword {
	return v.value
}

func (v *NullableMailPassword) Set(val *MailPassword) {
	v.value = val
	v.isSet = true
}

func (v NullableMailPassword) IsSet() bool {
	return v.isSet
}

func (v *NullableMailPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailPassword(val *MailPassword) *NullableMailPassword {
	return &NullableMailPassword{value: val, isSet: true}
}

func (v NullableMailPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


