/*
JQuants

JQuants

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jquants

import (
	"encoding/json"
)

// checks if the IDToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IDToken{}

// IDToken IDToken
type IDToken struct {
	IdToken *string `json:"idToken,omitempty"`
}

// NewIDToken instantiates a new IDToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIDToken() *IDToken {
	this := IDToken{}
	return &this
}

// NewIDTokenWithDefaults instantiates a new IDToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIDTokenWithDefaults() *IDToken {
	this := IDToken{}
	return &this
}

// GetIdToken returns the IdToken field value if set, zero value otherwise.
func (o *IDToken) GetIdToken() string {
	if o == nil || IsNil(o.IdToken) {
		var ret string
		return ret
	}
	return *o.IdToken
}

// GetIdTokenOk returns a tuple with the IdToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDToken) GetIdTokenOk() (*string, bool) {
	if o == nil || IsNil(o.IdToken) {
		return nil, false
	}
	return o.IdToken, true
}

// HasIdToken returns a boolean if a field has been set.
func (o *IDToken) HasIdToken() bool {
	if o != nil && !IsNil(o.IdToken) {
		return true
	}

	return false
}

// SetIdToken gets a reference to the given string and assigns it to the IdToken field.
func (o *IDToken) SetIdToken(v string) {
	o.IdToken = &v
}

func (o IDToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IDToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdToken) {
		toSerialize["idToken"] = o.IdToken
	}
	return toSerialize, nil
}

type NullableIDToken struct {
	value *IDToken
	isSet bool
}

func (v NullableIDToken) Get() *IDToken {
	return v.value
}

func (v *NullableIDToken) Set(val *IDToken) {
	v.value = val
	v.isSet = true
}

func (v NullableIDToken) IsSet() bool {
	return v.isSet
}

func (v *NullableIDToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIDToken(val *IDToken) *NullableIDToken {
	return &NullableIDToken{value: val, isSet: true}
}

func (v NullableIDToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIDToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


